namespace: ibm
name: ds8000
version: 1.0.0
readme: README.md
authors:
  - matancarmeli7 (github.com/matancarmeli7)
description: Ansible Collection for the IBM DS8000 family
license_file: LICENSE
tags:
  - ibm
  - ds8000
  - storage
dependencies: {}
repository: https://github.com/ansible-collections/ibm.ds8000
documentation: https://github.com/ansible-collections/ibm.ds8000/
homepage: https://github.com/ansible-collections/ibm.ds8000
issues: https://github.com/ansible-collections/ibm.ds8000/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
