name: Lint

on:
  push:
    branches:
      - main
      - stable-*
  pull_request:

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--line-length=160 --skip-string-normalization "
